# Generated by Django 6.0.7 on 2026-08-03 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Loja')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lojas', to=settings.AUTH_USER_MODEL, verbose_name='Responsável (Afiliado)')),
            ],
            options={
                'verbose_name': 'Loja',
                'verbose_name_plural': 'Lojas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome do Produto')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('sku', models.CharField(blank=True, max_length=50, verbose_name='SKU / Código Interno')),
                ('preco_custo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço de Custo (R$)')),
                ('preco_venda', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço de Venda (R$)')),
                ('quantidade_atual', models.IntegerField(default=0, verbose_name='Quantidade Atual em Estoque')),
                ('foto_principal', models.ImageField(blank=True, null=True, upload_to='produtos/principais/', verbose_name='Foto Principal')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo (Soft Delete)')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='estoque.loja', verbose_name='Loja')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada (Reposição)'), ('SAIDA', 'Saída (Venda)')], max_length=10, verbose_name='Tipo de Movimentação')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('preco_venda_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço de Venda Unitário (R$)')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data / Hora')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Responsável')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='estoque.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Movimentação de Estoque',
                'verbose_name_plural': 'Movimentações de Estoque',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ProdutoFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='produtos/secundarias/', verbose_name='Foto Secundária')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos_secundarias', to='estoque.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Foto Secundária do Produto',
                'verbose_name_plural': 'Fotos Secundárias do Produto',
            },
        ),
    ]
