# Generated by Django 6.0.7 on 2026-09-09 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='slug',
            field=models.SlugField(blank=True, help_text='Identificador único para a URL na loja (ex: iphone-15-pro-max)', max_length=150, null=True, unique=True, verbose_name='URL Personalizada (slug)'),
        ),
    ]
