# Generated by Django 5.2.17 on 2026-09-10 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_produto_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='forma_pagamento',
            field=models.CharField(blank=True, choices=[('PIX', 'PIX'), ('ESPECIE', 'Espécie (Dinheiro)'), ('CARTAO_DEBITO', 'Cartão de Débito'), ('CARTAO_CREDITO', 'Cartão de Crédito')], max_length=20, null=True, verbose_name='Forma de Pagamento'),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='parcelas',
            field=models.PositiveIntegerField(blank=True, default=1, help_text='Número de parcelas (apenas para Cartão de Crédito)', null=True, verbose_name='Parcelas'),
        ),
    ]
