# Generated by Django 6.0.7 on 2026-09-11 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_movimentacaoestoque_forma_pagamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='video',
            field=models.FileField(blank=True, help_text='Vídeo curto do produto (MP4 recomendado, máx. 50MB)', null=True, upload_to='produtos/videos/', verbose_name='Vídeo do Produto'),
        ),
    ]
