# Generated by Django 6.0.7 on 2026-09-11 22:44

import estoque.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_produto_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='video_com_audio',
            field=models.BooleanField(default=True, help_text='Se desmarcado, o vídeo será processado sem áudio (mudo).', verbose_name='Vídeo com áudio'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='video',
            field=models.FileField(blank=True, help_text='Vídeo curto do produto (máx. 15 segundos, MP4/MOV, máx. 50MB)', null=True, storage=estoque.models.get_video_storage, upload_to='produtos/videos/', verbose_name='Vídeo do Produto'),
        ),
    ]
